/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package clients.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class PositionString extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1651819559036848637L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PositionString\",\"namespace\":\"clients.avro\",\"fields\":[{\"name\":\"latitude\",\"type\":\"double\"},{\"name\":\"longitude\",\"type\":\"double\"},{\"name\":\"positionString\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PositionString> ENCODER =
      new BinaryMessageEncoder<PositionString>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PositionString> DECODER =
      new BinaryMessageDecoder<PositionString>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<PositionString> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<PositionString> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<PositionString> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PositionString>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this PositionString to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a PositionString from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a PositionString instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static PositionString fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public double latitude;
  @Deprecated public double longitude;
  @Deprecated public java.lang.String positionString;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PositionString() {}

  /**
   * All-args constructor.
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param positionString The new value for positionString
   */
  public PositionString(java.lang.Double latitude, java.lang.Double longitude, java.lang.String positionString) {
    this.latitude = latitude;
    this.longitude = longitude;
    this.positionString = positionString;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return latitude;
    case 1: return longitude;
    case 2: return positionString;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: latitude = (java.lang.Double)value$; break;
    case 1: longitude = (java.lang.Double)value$; break;
    case 2: positionString = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public double getLatitude() {
    return latitude;
  }


  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(double value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public double getLongitude() {
    return longitude;
  }


  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(double value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'positionString' field.
   * @return The value of the 'positionString' field.
   */
  public java.lang.String getPositionString() {
    return positionString;
  }


  /**
   * Sets the value of the 'positionString' field.
   * @param value the value to set.
   */
  public void setPositionString(java.lang.String value) {
    this.positionString = value;
  }

  /**
   * Creates a new PositionString RecordBuilder.
   * @return A new PositionString RecordBuilder
   */
  public static clients.avro.PositionString.Builder newBuilder() {
    return new clients.avro.PositionString.Builder();
  }

  /**
   * Creates a new PositionString RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PositionString RecordBuilder
   */
  public static clients.avro.PositionString.Builder newBuilder(clients.avro.PositionString.Builder other) {
    if (other == null) {
      return new clients.avro.PositionString.Builder();
    } else {
      return new clients.avro.PositionString.Builder(other);
    }
  }

  /**
   * Creates a new PositionString RecordBuilder by copying an existing PositionString instance.
   * @param other The existing instance to copy.
   * @return A new PositionString RecordBuilder
   */
  public static clients.avro.PositionString.Builder newBuilder(clients.avro.PositionString other) {
    if (other == null) {
      return new clients.avro.PositionString.Builder();
    } else {
      return new clients.avro.PositionString.Builder(other);
    }
  }

  /**
   * RecordBuilder for PositionString instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PositionString>
    implements org.apache.avro.data.RecordBuilder<PositionString> {

    private double latitude;
    private double longitude;
    private java.lang.String positionString;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(clients.avro.PositionString.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.latitude)) {
        this.latitude = data().deepCopy(fields()[0].schema(), other.latitude);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.longitude)) {
        this.longitude = data().deepCopy(fields()[1].schema(), other.longitude);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.positionString)) {
        this.positionString = data().deepCopy(fields()[2].schema(), other.positionString);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing PositionString instance
     * @param other The existing instance to copy.
     */
    private Builder(clients.avro.PositionString other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.latitude)) {
        this.latitude = data().deepCopy(fields()[0].schema(), other.latitude);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.longitude)) {
        this.longitude = data().deepCopy(fields()[1].schema(), other.longitude);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.positionString)) {
        this.positionString = data().deepCopy(fields()[2].schema(), other.positionString);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public double getLatitude() {
      return latitude;
    }


    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public clients.avro.PositionString.Builder setLatitude(double value) {
      validate(fields()[0], value);
      this.latitude = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public clients.avro.PositionString.Builder clearLatitude() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public double getLongitude() {
      return longitude;
    }


    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public clients.avro.PositionString.Builder setLongitude(double value) {
      validate(fields()[1], value);
      this.longitude = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public clients.avro.PositionString.Builder clearLongitude() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'positionString' field.
      * @return The value.
      */
    public java.lang.String getPositionString() {
      return positionString;
    }


    /**
      * Sets the value of the 'positionString' field.
      * @param value The value of 'positionString'.
      * @return This builder.
      */
    public clients.avro.PositionString.Builder setPositionString(java.lang.String value) {
      validate(fields()[2], value);
      this.positionString = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'positionString' field has been set.
      * @return True if the 'positionString' field has been set, false otherwise.
      */
    public boolean hasPositionString() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'positionString' field.
      * @return This builder.
      */
    public clients.avro.PositionString.Builder clearPositionString() {
      positionString = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PositionString build() {
      try {
        PositionString record = new PositionString();
        record.latitude = fieldSetFlags()[0] ? this.latitude : (java.lang.Double) defaultValue(fields()[0]);
        record.longitude = fieldSetFlags()[1] ? this.longitude : (java.lang.Double) defaultValue(fields()[1]);
        record.positionString = fieldSetFlags()[2] ? this.positionString : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PositionString>
    WRITER$ = (org.apache.avro.io.DatumWriter<PositionString>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PositionString>
    READER$ = (org.apache.avro.io.DatumReader<PositionString>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.latitude);

    out.writeDouble(this.longitude);

    out.writeString(this.positionString);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.latitude = in.readDouble();

      this.longitude = in.readDouble();

      this.positionString = in.readString();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.latitude = in.readDouble();
          break;

        case 1:
          this.longitude = in.readDouble();
          break;

        case 2:
          this.positionString = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}











