// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace app
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class ShakespeareValue : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"ShakespeareValue\",\"namespace\":\"app\",\"fields\":[{\"name\":\"l" +
				"ine_number\",\"doc\":\"The line number for line\",\"type\":\"int\"},{\"name\":\"line\",\"doc\":" +
				"\"The line from Shakespeare\",\"type\":\"string\"}]}");
		/// <summary>
		/// The line number for line
		/// </summary>
		private int _line_number;
		/// <summary>
		/// The line from Shakespeare
		/// </summary>
		private string _line;
		public virtual Schema Schema
		{
			get
			{
				return ShakespeareValue._SCHEMA;
			}
		}
		/// <summary>
		/// The line number for line
		/// </summary>
		public int line_number
		{
			get
			{
				return this._line_number;
			}
			set
			{
				this._line_number = value;
			}
		}
		/// <summary>
		/// The line from Shakespeare
		/// </summary>
		public string line
		{
			get
			{
				return this._line;
			}
			set
			{
				this._line = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.line_number;
			case 1: return this.line;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.line_number = (System.Int32)fieldValue; break;
			case 1: this.line = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
