plugins {
  id 'java'
  id 'application'
}

application {
    mainClass = 'clients.Producer'
}

repositories {
    mavenCentral()
    maven { url "https://packages.confluent.io/maven/" }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

dependencies {
    implementation group: 'org.apache.kafka', name: 'kafka-clients', version: '4.1.1'
    implementation group: 'org.slf4j', name: 'slf4j-reload4j', version: '2.0.16'
}
