// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace app
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class ShakespeareKey : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"ShakespeareKey\",\"namespace\":\"app\",\"fields\":[{\"name\":\"wor" +
				"k\",\"doc\":\"The name of the work\",\"type\":\"string\"},{\"name\":\"year\",\"doc\":\"The year " +
				"the work was published\",\"type\":\"int\"}]}");
		/// <summary>
		/// The name of the work
		/// </summary>
		private string _work;
		/// <summary>
		/// The year the work was published
		/// </summary>
		private int _year;
		public virtual Schema Schema
		{
			get
			{
				return ShakespeareKey._SCHEMA;
			}
		}
		/// <summary>
		/// The name of the work
		/// </summary>
		public string work
		{
			get
			{
				return this._work;
			}
			set
			{
				this._work = value;
			}
		}
		/// <summary>
		/// The year the work was published
		/// </summary>
		public int year
		{
			get
			{
				return this._year;
			}
			set
			{
				this._year = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.work;
			case 1: return this.year;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.work = (System.String)fieldValue; break;
			case 1: this.year = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
